{{- range .Values.clusters }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .name }}-argocd"
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: eso-admin-secret-store
    kind: ClusterSecretStore
  target:
    name: "{{ .name }}-argocd-token"
  data:
  - secretKey: "{{ .stage }}_ARGOCD_TOKEN"
    remoteRef:
      key: "{{ .name }}/argocd"
      property: ARGOCD_TOKEN
{{- end }}