# https://www.npmjs.com/package/@backstage-community/plugin-rbac-backend
## Example multiple conditionals
apiVersion: v1
kind: ConfigMap
metadata:
  name: rbac-conditional-policies
data:
  policies.yaml: |
    # ---
    # result: CONDITIONAL
    # roleEntityRef: role:default/developers
    # pluginId: catalog
    # resourceType: catalog-entity
    # permissionMapping:
    #   - read
    # conditions:
    #   anyOf:
    #     - rule: HAS_SPEC
    #       resourceType: catalog-entity
    #       params:
    #         key: type
    #         value: service
    #     - rule: HAS_SPEC
    #       resourceType: catalog-entity
    #       params:
    #         key: type
    #         value: workshop
    #     - rule: IS_ENTITY_KIND
    #       resourceType: catalog-entity
    #       params:
    #         kinds:
    #           - User
    #           - Group
    #           # - Component
    #           # - System
    #           # - Resource
    #           # - API
    #           # - Location
    # ---
    # result: CONDITIONAL
    # roleEntityRef: role:default/cluster-admins
    # pluginId: catalog
    # resourceType: catalog-entity
    # permissionMapping:
    #   - read
    # conditions:
    #   anyOf:
    #     - rule: HAS_SPEC
    #       resourceType: catalog-entity
    #       params:
    #         key: type
    #         value: service
    #     - rule: HAS_SPEC
    #       resourceType: catalog-entity
    #       params:
    #         key: type
    #         value: workshop