apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: "{{ .Values.notebookName }}"
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    opendatahub.io/dashboard: "true"
  name: "{{ .Values.notebookName }}"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.storageSize }}"
  storageClassName: gp3
  volumeMode: Filesystem
