{{ if .Values.dataConnection.create }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "aws-connection-{{ .Values.dataConnection.name }}"
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: "{{ .Values.clusterSecretStoreName }}"
    kind: ClusterSecretStore
  target:
    name: "aws-connection-{{ .Values.dataConnection.name }}"
    template:
      metadata:
        labels:
          opendatahub.io/dashboard: "true"
          opendatahub.io/managed: "true"
        annotations:
          opendatahub.io/connection-type: s3
          openshift.io/display-name: "{{ .Values.dataConnection.name }}"
      type: generic
      data:
        AWS_ACCESS_KEY_ID: "{{`{{ .AWS_ACCESS_KEY_ID }}`}}"
        AWS_DEFAULT_REGION: "{{`{{ .AWS_DEFAULT_REGION }}`}}"
        AWS_S3_BUCKET: "{{`{{ .AWS_S3_BUCKET }}`}}"
        AWS_S3_ENDPOINT: "{{`{{ .AWS_S3_ENDPOINT }}`}}"
        AWS_SECRET_ACCESS_KEY: "{{`{{ .AWS_SECRET_ACCESS_KEY }}`}}"
  data:
    - secretKey: "AWS_ACCESS_KEY_ID"
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        metadataPolicy: None
        key: "{{ .Values.dataConnection.name }}"
        property: AWS_ACCESS_KEY_ID
    - secretKey: "AWS_DEFAULT_REGION"
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        metadataPolicy: None
        key: "{{ .Values.dataConnection.name }}"
        property: AWS_DEFAULT_REGION
    - secretKey: "AWS_S3_BUCKET"
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        metadataPolicy: None
        key: "{{ .Values.dataConnection.name }}"
        property: AWS_S3_BUCKET
    - secretKey: "AWS_S3_ENDPOINT"
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        metadataPolicy: None
        key: "{{ .Values.dataConnection.name }}"
        property: AWS_S3_ENDPOINT
    - secretKey: "AWS_SECRET_ACCESS_KEY"
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        metadataPolicy: None
        key: "{{ .Values.dataConnection.name }}"
        property: AWS_SECRET_ACCESS_KEY
{{ end }}