{{- if .Values.provider }}
{{- if .Values.provider.azure}}
apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: eso-admin-secret-store
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  namespaces: []
  provider:
    azurekv:
      tenantId: "{{ .Values.provider.azure.tenant_id }}"
      vaultUrl: "{{ .Values.provider.azure.vault_url }}"
      authSecretRef:
        clientId:
          name: eso-admin-secret
          namespace: "{{ .Values.namespace }}"
          key: client-id
        clientSecret:
          name: eso-admin-secret
          namespace: "{{ .Values.namespace }}"
          key: client-secret
---
apiVersion: v1
data:
  client-id: "{{ .Values.provider.azure.client_id | b64enc  }}"
  client-secret: "{{ .Values.provider.azure.client_secret | b64enc  }}"
kind: Secret
metadata:
  name: eso-admin-secret
  namespace: "{{ .Values.namespace }}"
{{- end }}
{{- end }}