{{- if .Values.k8s }}
{{- if .Values.k8s.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: kubernetes-secrets-store
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    kubernetes:
      remoteNamespace: "{{ .Values.k8s.target.namespace }}"
      server:
        url: https://kubernetes.default.svc
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: "{{ .Values.k8s.target.namespace }}"
          key: ca.crt
      auth:
        serviceAccount:
          name: "{{ .Values.k8s.target.serviceaccount }}"
          namespace: "{{ .Values.k8s.target.namespace }}"
{{- end }}
{{- end }}
